# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import dialog_server_pb2 as dialog__server__pb2


class DialogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendReply = channel.unary_unary(
                '/DialogService/SendReply',
                request_serializer=dialog__server__pb2.Reply.SerializeToString,
                response_deserializer=dialog__server__pb2.Reply.FromString,
                )
        self.GetReplyHistoryLimited = channel.unary_unary(
                '/DialogService/GetReplyHistoryLimited',
                request_serializer=dialog__server__pb2.GetReplyHistoryLimitedParam.SerializeToString,
                response_deserializer=dialog__server__pb2.ReplyHistoryLimited.FromString,
                )
        self.GetReplyHistory = channel.unary_stream(
                '/DialogService/GetReplyHistory',
                request_serializer=dialog__server__pb2.GetReplyHistoryParam.SerializeToString,
                response_deserializer=dialog__server__pb2.Reply.FromString,
                )


class DialogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplyHistoryLimited(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplyHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DialogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendReply': grpc.unary_unary_rpc_method_handler(
                    servicer.SendReply,
                    request_deserializer=dialog__server__pb2.Reply.FromString,
                    response_serializer=dialog__server__pb2.Reply.SerializeToString,
            ),
            'GetReplyHistoryLimited': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplyHistoryLimited,
                    request_deserializer=dialog__server__pb2.GetReplyHistoryLimitedParam.FromString,
                    response_serializer=dialog__server__pb2.ReplyHistoryLimited.SerializeToString,
            ),
            'GetReplyHistory': grpc.unary_stream_rpc_method_handler(
                    servicer.GetReplyHistory,
                    request_deserializer=dialog__server__pb2.GetReplyHistoryParam.FromString,
                    response_serializer=dialog__server__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DialogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DialogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DialogService/SendReply',
            dialog__server__pb2.Reply.SerializeToString,
            dialog__server__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReplyHistoryLimited(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DialogService/GetReplyHistoryLimited',
            dialog__server__pb2.GetReplyHistoryLimitedParam.SerializeToString,
            dialog__server__pb2.ReplyHistoryLimited.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReplyHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/DialogService/GetReplyHistory',
            dialog__server__pb2.GetReplyHistoryParam.SerializeToString,
            dialog__server__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
