# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dialog_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64ialog_server.proto\",\n\x05Reply\x12\x12\n\nspeaker_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63omment\x18\x02 \x01(\t\"G\n\x1bGetReplyHistoryLimitedParam\x12\x12\n\nspeaker_id\x18\x01 \x01(\t\x12\x14\n\x0chistory_from\x18\x02 \x01(\x05\"*\n\x14GetReplyHistoryParam\x12\x12\n\nspeaker_id\x18\x01 \x01(\t\".\n\x13ReplyHistoryLimited\x12\x17\n\x07replies\x18\x03 \x03(\x0b\x32\x06.Reply\"\x1c\n\x05\x45mpty\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x32\xae\x01\n\rDialogService\x12\x1b\n\tSendReply\x12\x06.Reply\x1a\x06.Reply\x12L\n\x16GetReplyHistoryLimited\x12\x1c.GetReplyHistoryLimitedParam\x1a\x14.ReplyHistoryLimited\x12\x32\n\x0fGetReplyHistory\x12\x15.GetReplyHistoryParam\x1a\x06.Reply0\x01\x62\x06proto3')



_REPLY = DESCRIPTOR.message_types_by_name['Reply']
_GETREPLYHISTORYLIMITEDPARAM = DESCRIPTOR.message_types_by_name['GetReplyHistoryLimitedParam']
_GETREPLYHISTORYPARAM = DESCRIPTOR.message_types_by_name['GetReplyHistoryParam']
_REPLYHISTORYLIMITED = DESCRIPTOR.message_types_by_name['ReplyHistoryLimited']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'dialog_server_pb2'
  # @@protoc_insertion_point(class_scope:Reply)
  })
_sym_db.RegisterMessage(Reply)

GetReplyHistoryLimitedParam = _reflection.GeneratedProtocolMessageType('GetReplyHistoryLimitedParam', (_message.Message,), {
  'DESCRIPTOR' : _GETREPLYHISTORYLIMITEDPARAM,
  '__module__' : 'dialog_server_pb2'
  # @@protoc_insertion_point(class_scope:GetReplyHistoryLimitedParam)
  })
_sym_db.RegisterMessage(GetReplyHistoryLimitedParam)

GetReplyHistoryParam = _reflection.GeneratedProtocolMessageType('GetReplyHistoryParam', (_message.Message,), {
  'DESCRIPTOR' : _GETREPLYHISTORYPARAM,
  '__module__' : 'dialog_server_pb2'
  # @@protoc_insertion_point(class_scope:GetReplyHistoryParam)
  })
_sym_db.RegisterMessage(GetReplyHistoryParam)

ReplyHistoryLimited = _reflection.GeneratedProtocolMessageType('ReplyHistoryLimited', (_message.Message,), {
  'DESCRIPTOR' : _REPLYHISTORYLIMITED,
  '__module__' : 'dialog_server_pb2'
  # @@protoc_insertion_point(class_scope:ReplyHistoryLimited)
  })
_sym_db.RegisterMessage(ReplyHistoryLimited)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'dialog_server_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

_DIALOGSERVICE = DESCRIPTOR.services_by_name['DialogService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REPLY._serialized_start=23
  _REPLY._serialized_end=67
  _GETREPLYHISTORYLIMITEDPARAM._serialized_start=69
  _GETREPLYHISTORYLIMITEDPARAM._serialized_end=140
  _GETREPLYHISTORYPARAM._serialized_start=142
  _GETREPLYHISTORYPARAM._serialized_end=184
  _REPLYHISTORYLIMITED._serialized_start=186
  _REPLYHISTORYLIMITED._serialized_end=232
  _EMPTY._serialized_start=234
  _EMPTY._serialized_end=262
  _DIALOGSERVICE._serialized_start=265
  _DIALOGSERVICE._serialized_end=439
# @@protoc_insertion_point(module_scope)
