# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16inference_server.proto\"_\n\x07\x43omment\x12\x0f\n\x07\x63omment\x18\x01 \x01(\t\x12\x15\n\rcomment_past1\x18\x02 \x01(\t\x12\x15\n\rcomment_past2\x18\x03 \x01(\t\x12\x15\n\rcomment_past3\x18\x04 \x01(\t\"\x16\n\x05Reply\x12\r\n\x05reply\x18\x01 \x01(\t20\n\x10InferenceService\x12\x1c\n\x08GetReply\x12\x08.Comment\x1a\x06.Replyb\x06proto3')



_COMMENT = DESCRIPTOR.message_types_by_name['Comment']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
Comment = _reflection.GeneratedProtocolMessageType('Comment', (_message.Message,), {
  'DESCRIPTOR' : _COMMENT,
  '__module__' : 'inference_server_pb2'
  # @@protoc_insertion_point(class_scope:Comment)
  })
_sym_db.RegisterMessage(Comment)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'inference_server_pb2'
  # @@protoc_insertion_point(class_scope:Reply)
  })
_sym_db.RegisterMessage(Reply)

_INFERENCESERVICE = DESCRIPTOR.services_by_name['InferenceService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMENT._serialized_start=26
  _COMMENT._serialized_end=121
  _REPLY._serialized_start=123
  _REPLY._serialized_end=145
  _INFERENCESERVICE._serialized_start=147
  _INFERENCESERVICE._serialized_end=195
# @@protoc_insertion_point(module_scope)
