# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import dialog_server_pb2 as dialog__server__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16inference_server.proto\x1a\x13\x64ialog_server.proto\"#\n\x07\x43omment\x12\x18\n\x08\x63omments\x18\x01 \x03(\x0b\x32\x06.Reply20\n\x10InferenceService\x12\x1c\n\x08GetReply\x12\x08.Comment\x1a\x06.Replyb\x06proto3')



_COMMENT = DESCRIPTOR.message_types_by_name['Comment']
Comment = _reflection.GeneratedProtocolMessageType('Comment', (_message.Message,), {
  'DESCRIPTOR' : _COMMENT,
  '__module__' : 'inference_server_pb2'
  # @@protoc_insertion_point(class_scope:Comment)
  })
_sym_db.RegisterMessage(Comment)

_INFERENCESERVICE = DESCRIPTOR.services_by_name['InferenceService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COMMENT._serialized_start=47
  _COMMENT._serialized_end=82
  _INFERENCESERVICE._serialized_start=84
  _INFERENCESERVICE._serialized_end=132
# @@protoc_insertion_point(module_scope)
