version: "3"

services:
    dialog_server:
        build:
            context: .
            dockerfile: dialog_server/Dockerfile
        image: dialog_server_image
        container_name: dialog-server
        ports:
            - "8080:8080"
        volumes:
            - ../src/:/app/src:Z
            - ../test:/app/test:Z
        command: ["bash", "-xc", "cd /app/src/ && python3 run_dialog_server.py"]
        networks:
            - app-net

    inference_server:
        build:
            context: .
            dockerfile: inference_server/Dockerfile
        image: inference_server_image
        container_name: inference-server
        ports:
            - "8001:8001"
        volumes:
            - ../src/:/app/src:Z
            - ../test:/app/test:Z
            - ./inference_server/model:/model
            - ./inference_server/data:/data
        command:
            ["bash", "-xc", "cd /app/src/ && python3 run_inference_server.py"]
        networks:
            - app-net
    # redis:
    #     image: "redis:latest"
    #     container_name: redis
    #     ports:
    #         - "6379:6379"
    #     volumes:
    #         - "redis_data"
    #     networks:
    #         - app-net

volumes:
    redis_data:

networks:
    app-net:
        driver: bridge
